---
#Ansible conditonal operators
# == Equal
# < Lessthan
# > Greaterthan
# <= Lessthan or equal to
# >= Greaterthan or equal to
# != Not equal to
# Variable exist i.e,.. is defined
# example: "{{myvar}}" is defined"
# Variable doesn't exist i.e,.. is not defined
# example: "{{myvar}}" is not defined"
# 'and', 'or', 'not' logical operators
# 'in' operator
# Example: "{{user}} in [Roshan,Sanjay,Siva,Mani,Uday]"
- name: Play book to demonstrate Ansible conditonal operators
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   fname: /etc/passwd
  tasks:
   - name: Check if file exists 
     stat:
      path: "{{fname}}"
     register: out
     ignore_errors: yes
   - name: Print if file exists
     debug:
      msg: File "{{fname}}" Exists
     when: out.stat.exists
   - name: Print if file doesn't exists
     debug:
      msg: File "{{fname}}" does not Exists
     when: out.stat.exists == false
...