---
- name: Play to demonstrate if variable is defined
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   dname: /Samson
  tasks:
   - name: Check if directory {{dname}} exists with stat module
     stat:
      path: "{{dname}}"
     register: out
   - name: See if the directory exits now.
     shell: ls "{{dname}}"
     when: out.stat.exists and out.stat.isdir
     register: out1
   - name:
     debug:
      var: out1
...  